/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication33;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QL extends javax.swing.JFrame {

    /**
     * Creates new form QL
     */
    public QL() {
        initComponents();
        filltable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        tk = new javax.swing.JTextField();
        pas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nn = new javax.swing.JRadioButton();
        na = new javax.swing.JRadioButton();
        nv = new javax.swing.JRadioButton();
        nk = new javax.swing.JRadioButton();
        cs = new javax.swing.JRadioButton();
        cc = new javax.swing.JRadioButton();
        ft = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mã", "họ tên", "tuổi", "giới tính", "tài khoản", "password", "Loại nv", "Ca làm"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        jLabel1.setText("Mã nv");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        jLabel4.setText("Gender");

        jLabel5.setText("Role");

        jLabel6.setText("Time");

        jLabel7.setText("Tải khoản");

        jLabel8.setText("Password");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup2.add(nn);
        nn.setSelected(true);
        nn.setText("nam");
        nn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnActionPerformed(evt);
            }
        });

        buttonGroup2.add(na);
        na.setText("nu");

        buttonGroup1.add(nv);
        nv.setSelected(true);
        nv.setText("Nhân viên");

        buttonGroup1.add(nk);
        nk.setText("Nhân viên kho");

        buttonGroup3.add(cs);
        cs.setText("7h-11h");

        buttonGroup3.add(cc);
        cc.setText("13h-17h");

        buttonGroup3.add(ft);
        ft.setSelected(true);
        ft.setText("fulltime");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nv)
                    .addComponent(nn)
                    .addComponent(cs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cc)
                        .addGap(18, 18, 18)
                        .addComponent(ft))
                    .addComponent(na)
                    .addComponent(nk))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nn)
                    .addComponent(na))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nv)
                    .addComponent(nk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cs)
                    .addComponent(cc)
                    .addComponent(ft))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("new");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tk, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
index=tbl.getSelectedRow();
model=(DefaultTableModel)tbl.getModel();
id.setText(model.getValueAt(tbl.getSelectedRow(), 0).toString());
id.setEnabled(false);
name.setText(model.getValueAt(tbl.getSelectedRow(), 1).toString());
age.setText(model.getValueAt(tbl.getSelectedRow(), 2).toString());
if(model.getValueAt(tbl.getSelectedRow(), 3).equals("nam")){nn.setSelected(true);na.setSelected(false);}
if(model.getValueAt(tbl.getSelectedRow(), 3).equals("nu")){na.setSelected(true);nn.setSelected(false);}
if(model.getValueAt(tbl.getSelectedRow(), 6).equals("nhan vien")){nv.setSelected(true);nk.setSelected(false);}
if(model.getValueAt(tbl.getSelectedRow(), 6).equals("nhan vien kho")){nk.setSelected(true);nv.setSelected(false);}
if(model.getValueAt(tbl.getSelectedRow(), 7).equals("7h-11h")){cs.setSelected(true);cc.setSelected(false);ft.setSelected(false);}
if(model.getValueAt(tbl.getSelectedRow(), 7).equals("13h-17h")){cc.setSelected(true);cs.setSelected(false);ft.setSelected(false);}
if(model.getValueAt(tbl.getSelectedRow(), 7).equals("fulltime")){ft.setSelected(true);cs.setSelected(false);cc.setSelected(false);}
tk.setText(model.getValueAt(tbl.getSelectedRow(), 4).toString());
tk.setEnabled(false);
pas.setText(model.getValueAt(tbl.getSelectedRow(), 5).toString());
tbl.setRowSelectionInterval(index, index);
// TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void nnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
id.setText(""); 
id.setEnabled(true);
name.setText("");
age.setText("");
tk.setText("");
tk.setEnabled(true);
pas.setText("");
nn.setSelected(true);
ft.setSelected(true);
nv.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
checknull();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        if (nv.isSelected()) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
                Connection con = DriverManager.getConnection(url);
                String sql = "Delete from nhanvien where taikhoan =? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, tk.getText());
                pst.executeUpdate();
                pst.close();
                con.close();
            } catch (Exception e) {
            }
        }
        if (nv.isSelected()) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
                Connection con = DriverManager.getConnection(url);
                String sql = "Delete from nhanvienkho where taikhoan =? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, tk.getText());
                pst.executeUpdate();
                pst.close();
                con.close();
            } catch (Exception e) {
            }
        }
        int n = JOptionPane.showConfirmDialog(this, "You Sure?");
        if (n == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
                Connection con = DriverManager.getConnection(url);
                int x = tbl.getSelectedRow();
                lst.remove(x);
                model = (DefaultTableModel) tbl.getModel();
                model.removeRow(x);
                String sql = "Delete from nv where manv =? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, id.getText());
                pst.executeUpdate();
                pst.close();
                con.close();
                JOptionPane.showMessageDialog(this, "done!!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (index != tbl.getSelectedRow()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sinh viên");
        } else {
            check();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cc;
    private javax.swing.JRadioButton cs;
    private javax.swing.JRadioButton ft;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton na;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton nk;
    private javax.swing.JRadioButton nn;
    private javax.swing.JRadioButton nv;
    private javax.swing.JTextField pas;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tk;
    // End of variables declaration//GEN-END:variables
ArrayList<Nhanvien> lst= new ArrayList<>();
    DefaultTableModel model;
    int index;
    
    public ArrayList<Nhanvien> lst()
    {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url="jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
            Connection con =DriverManager.getConnection(url);
            String sql="select * from nv";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                Nhanvien nv = new Nhanvien(rs.getString(1), rs.getString(2), rs.getInt(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8));
                lst.add(nv);
            }     
            
        } catch (Exception e) {
        }
        return lst;
    }
    public void filltable()
    {
        ArrayList<Nhanvien> lst=lst();
        model=(DefaultTableModel)tbl.getModel();
        for(Nhanvien x:lst)
        {
            model.addRow(new Object[]{x.id,x.name,x.tuoi,x.gt,x.taik,x.password,x.chucvu,x.hlam});
        }
    }
    public void checknull()
    {
        try {
            String ten=name.getText();
            String check="[a-zA-Z]{3,}*";
            if(!ten.matches(check)){JOptionPane.showMessageDialog(this, "tên người là chữ");name.requestFocus();return;}

        } catch (Exception e) {
        }

        
        try {
        
        if(id.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");id.requestFocus();return;}
        if(name.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");name.requestFocus();return;}
        if(age.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");age.requestFocus();return;}
        if(nn.isSelected()==false && na.isSelected()==false){JOptionPane.showMessageDialog(this, "gioi tinh???");return;}
        if(nv.isSelected()==false && nk.isSelected()==false){JOptionPane.showMessageDialog(this, "loai nv???");return;}
        if(cs.isSelected()==false && cc.isSelected()==false && ft.isSelected()==false){JOptionPane.showMessageDialog(this, "h lam");return;}
        if(tk.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");tk.requestFocus();return;}
        if(pas.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");pas.requestFocus();return;}

        } catch (Exception e) {
        }
        
                
        try {
            int t = Integer.parseInt(age.getText());
            if(t<18){JOptionPane.showMessageDialog(this, "tuoi>18");age.requestFocus();return;}
                    
        else
        {
            try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
            Connection con = DriverManager.getConnection(url);
            String sql="insert into nv values (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id.getText());
            pst.setString(2, name.getText());
            pst.setString(3, age.getText());
            if(nn.isSelected()){pst.setString(4, "nam");}
            if(na.isSelected()){pst.setString(4, "nu");}
            pst.setString(5, tk.getText());
            pst.setString(6, pas.getText());
            if(nv.isSelected()){pst.setString(7, "nhan vien");}
            if(nk.isSelected()){pst.setString(7, "nhan vien kho");}
            if(cs.isSelected()){pst.setString(8, "7h-11h");}
            if(cc.isSelected()){pst.setString(8, "13h-17h");}
            if(ft.isSelected()){pst.setString(8, "fulltime");}
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(this, "done");
            save();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "mã đã tồn tại");
        }
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url="jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
        Connection con =DriverManager.getConnection(url);
        if(nv.isSelected())
        {
            String sql="insert into nhanvien values(?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, tk.getText());
            pst.setString(2, pas.getText());
            pst.executeUpdate();
        }
        
        if(nk.isSelected())
        {
            String sql="insert into nhanvienkho values(?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, tk.getText());
            pst.setString(2, pas.getText());
            pst.executeUpdate();
        }
        con.close();
        } catch (Exception e) {
            
        }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "tuổi là số");
        }
        
    }
    public void save()
    {
        try {
            String i = id.getText();
            String n = name.getText();
            int y = Integer.parseInt(age.getText());
            String gt = null;
            if (nn.isSelected()) {
                gt = "nam";
            }
            if (na.isSelected()) {
                gt = "nu";
            }
            String cv = null;
            if (nv.isSelected()) {
                cv = "nhan vien";
            }
            if (nk.isSelected()) {
                cv = "nhan vien kho";
            }
            String cl = null;
            if (cs.isSelected()) {
                cl = "7h-11h";
            }
            if (cc.isSelected()) {
                cl = "13h-17h";
            }
            if (ft.isSelected()) {
                cl = "fulltime";
            }
            String t = tk.getText();
            String p = pas.getText();
            Nhanvien nv = new Nhanvien(i, n, y, gt, t, p, cv, cl);
            lst.add(nv);
            model.addRow(new Object[]{i, n, y, gt, t, p, cv, cl});
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "đã tồn tại mã nv");
        }
    }
    
    public void updatesql()
    {
        try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
                Connection con = DriverManager.getConnection(url);
                String sql = "update nv set tuoi=?,gioitinh=?,password=?,chucvu=?,calam=? where hoten=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, age.getText());
                if (nn.isSelected()) {
                    pst.setString(2, "nam");
                }
                if (na.isSelected()) {
                    pst.setString(2, "nu");
                }
                pst.setString(3, pas.getText());
                if (nv.isSelected()) {
                    pst.setString(4, "nhan vien");
                }
                if (nk.isSelected()) {
                    pst.setString(4, "nhan vien kho");
                }
                if (cs.isSelected()) {
                    pst.setString(5, "7h-11h");
                }
                if (cc.isSelected()) {
                    pst.setString(5, "13h-17h");
                }
                if (ft.isSelected()) {
                    pst.setString(5, "fulltime");
                }
                pst.setString(6, name.getText());
                pst.executeUpdate();
                pst.close();
                update();
                JOptionPane.showMessageDialog(this, "done");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            if (nv.isSelected()) {
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = "jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
                    Connection con = DriverManager.getConnection(url);
                    String sql = "update nhanvien set password=? where taikhoan=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, pas.getText());
                    pst.setString(2, tk.getText());
                    pst.executeUpdate();
                } catch (Exception e) {
                }
            }

            if (nk.isSelected()) {
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = "jdbc:sqlserver://127.0.0.1;user=sa;password=123;Database=DK_Agile";
                    Connection con = DriverManager.getConnection(url);
                    String sql = "update nhanvienkho set password=? where taikhoan=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, pas.getText());
                    pst.setString(2, tk.getText());
                    pst.executeUpdate();
                } catch (Exception e) {
                }
            }
    }
    public void update()
    {
        model = (DefaultTableModel) tbl.getModel();
        model.setValueAt(name.getText(), tbl.getSelectedRow(), 1);
        model.setValueAt(age.getText(), tbl.getSelectedRow(), 2);
        model.setValueAt(pas.getText(), tbl.getSelectedRow(), 5);
        if(nn.isSelected()){model.setValueAt("nam", tbl.getSelectedRow(), 3);}
        if(na.isSelected()){model.setValueAt("nu", tbl.getSelectedRow(), 3);}
        if(nv.isSelected()){model.setValueAt("nhan vien", tbl.getSelectedRow(), 6);}
        if(nk.isSelected()){model.setValueAt("nhan vien kho", tbl.getSelectedRow(), 6);}
        if(cs.isSelected()){model.setValueAt("7h-11h", tbl.getSelectedRow(), 7);}
        if(cc.isSelected()){model.setValueAt("13h-17h", tbl.getSelectedRow(), 7);}
        if(ft.isSelected()){model.setValueAt("fulltime", tbl.getSelectedRow(), 7);}
    }
    public void check()
    {
        try {
            String ten=name.getText();
            String check="[a-zA-Z]{3,}*";
            if(!ten.matches(check)){JOptionPane.showMessageDialog(this, "tên người là chữ");name.requestFocus();return;}

        } catch (Exception e) {
        }
        
        try {
            int t = Integer.parseInt(age.getText());
            if(t<18){JOptionPane.showMessageDialog(this, "tuoi>18");age.requestFocus();return;}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "tuổi là số");
        }
        
        try {
        
        if(id.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");id.requestFocus();return;}
        if(name.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");name.requestFocus();return;}
        if(age.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");age.requestFocus();return;}
        if(nn.isSelected()==false && na.isSelected()==false){JOptionPane.showMessageDialog(this, "gioi tinh???");return;}
        if(nv.isSelected()==false && nk.isSelected()==false){JOptionPane.showMessageDialog(this, "loai nv???");return;}
        if(cs.isSelected()==false && cc.isSelected()==false && ft.isSelected()==false){JOptionPane.showMessageDialog(this, "h lam");return;}
        if(tk.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");tk.requestFocus();return;}
        if(pas.getText().equals("")){JOptionPane.showMessageDialog(this, "trống");pas.requestFocus();return;} 
        else
        {updatesql();}
        
        }
        catch (Exception e) {
                }
    }
}
